@startuml screens

SC01001:ログイン画面

SC02011:取引先一覧画面
SC02012:取引先詳細画面
SC02021:取引先入力画面（登録モード）
SC02022:取引先入力画面（更新モード）
SC02031:取引先確認画面  

SC03011:担当者一覧画面
SC03012:担当者詳細画面
SC03021:担当者入力画面（登録モード）
SC03022:担当者入力画面（更新モード）
SC03031:担当者確認画面

@enduml